import META from './meta.mjs';
import Validator from './validator.mjs';
import ModelError from './model-error.mjs';

import mongo from 'mongodb';

import assert from 'assert';
import util from 'util';


/** 

All detected errors should be reported by throwing an array of
ModelError objects.  

Errors are of two types:

  + *Local errors* depend only on the field values of the current data
    item.  Local errors are specified and checked using meta.mjs
    and validator.mjs and are not specified below.

  + *Global errors* depend on data items other than the current data
    item.  The comments for the code below document global errors.

Each ModelError must be specified with an error code (defined below)
and an error message which should be as specific as possible.  If the
error is associated with a particular field, then the internal name of
that field should be filled in to the ModelError object.  Note that if
an error message refers to the name of the field, it should do so
using the external name (`title`) of the field.

The codes for the ModelError include the following:

BAD_ACT:
  Action does not correspond to one of the model action routines.

BAD_FIELD:
  An object contains an unknown field name or a forbidden field.

BAD_FIELD_VALUE:
  The value of a field does not meet its specs.

BAD_ID:
  Object not found for specified ID.  Includes an error when some field 
  specifies an id for some other object, but there is no object having
  that ID.

DB:
  Database error

FORM_ERROR:
  Form is invalid.

MISSING_FIELD:
  The value of a required field is not specified.

*/

export default class Model {

  /** Set up properties from props as properties of this. */
  constructor(props) {
    Object.assign(this, props);
  }

  get DEFAULT_COUNT() { return COUNT; }

  /** Return a new instance of Model set up to use database specified
   *  by dbUrl
   */ 
  static async make(dbUrl) {
    let client;
    try {
      client = await mongo.connect(dbUrl, MONGO_CONNECT_OPTIONS );
      const db = client.db();
      const books = db.collection(BOOKS);
      const carts = db.collection(CARTS);
      await books.createIndex({ title: 'text', authors: 'text', });
      const props = {
	client, db, books, carts, meta: META,
	validator: new Validator(META),
      };
      const model = new Model(props);
      return model;
    }
    catch (err) {
      const msg = `cannot connect to URL "${dbUrl}": ${err}`;
      throw [ new ModelError('DB', msg) ];
    }
  }

  /** Release all resources held by this model.  Specifically,
   *  close any database connections.
   */
  async close() {
    await this.client.close();
  }

  /** Clear out all data stored within this model. */
  async clear() {
    try {
      await this.books.deleteMany({});
      await this.carts.deleteMany({});
    }
    catch (err) {
      throw [ new ModelError('DB', err.message || err.toString()) ];
    }
  }
  
  //Action routines

  /** Create a new cart.  Returns ID of newly created cart.  The
   * returned ID should not be generated by the database; it should
   * also not be easily guessable.
   *
   *  The new cart should have a `_lastModified` field set to the
   *  current Date timestamp.
   */
  async newCart(rawNameValues) {
    const nameValues = this._validate('newCart', rawNameValues);
    try {
      const _id = String((await this.carts.countDocuments({})) + Math.random());
      await this.carts.insertOne({_id, _lastModified: new Date(), });
      return _id;
    }
    catch (err) {
      throw [ new ModelError('DB', err.message || err.toString()) ];
    }
  }

  /** Given fields { cartId, sku, nUnits } = rawNameValues, update
   *  number of units for sku to nUnits.  Update `_lastModified` field
   *  of cart to current Date timestamp.
   *
   *  Global Errors:
   *    BAD_ID: cartId does not reference a cart.
   *            sku does not specify the isbn of an existing book.
   */
  async cartItem(rawNameValues) {
    const nameValues = this._validate('cartItem', rawNameValues);
    try {
      const { cartId: _id, sku, nUnits } = nameValues;
      const books = await this.findBooks({isbn: sku});
      if (books.length !== 1) {
	throw [ new ModelError('BAD_ID', `unknown sku ${sku}`, 'sku'), ];
      }
      const update = {
	$currentDate: { _lastModified: true, },
	$set: { [sku]: nUnits }
      };
      const result = await this.carts.updateOne({ _id, }, update);
      if (result.matchedCount !== 1) {
	const msg = `no updates for cart "${_id}"`;
	throw [ new ModelError('BAD_ID', msg, 'cartId'), ];
      }
    }
    catch (err) {
      if (err instanceof Array) throw err;
      throw [ new ModelError('DB', err.message || err.toString()) ];
    }
  }
  
  /** Given fields { cartId } = nameValues, return cart identified by
   *  cartId.  The cart is returned as an object which contains a
   *  mapping from SKU's to *positive* integers (representing the
   *  number of units of the item identified by the SKU contained in
   *  the cart).  Addtionally, it must also have a `_lastModified`
   *  property containing a Date timestamp specifying the last time the
   *  cart was modified.
   *
   *  Globals Errors:
   *    BAD_ID: cartId does not reference a cart.
   */
  async getCart(rawNameValues) {
    const nameValues = this._validate('getCart', rawNameValues);
    try {
      const { cartId: _id, } = nameValues;
      const result = await this.carts.findOne({_id});
      if (result === null) {
	const msg = `cannot find cart "${_id}"`;
	throw [ new ModelError('BAD_ID', msg, 'cartId'), ];
      }
      const items =
        Object.entries(result).filter(([k, v]) => k !== '_id' && v > 0);
      return Object.fromEntries(items);
    }
    catch (err) {
      if (err instanceof Array) throw err;
      throw [ new ModelError('DB', err.message || err.toString()) ];
    }
    return {};
  }

  /** Given fields { isbn, title, authors, publisher, year, pages } =
   *  nameValues for a book, add the book to this model.  The isbn
   *  field should uniquely identify the book.  Note that if the book
   *  already exists in this model, then this routine should merely
   *  update the information associated with the book.
   *
   *  Returns the isbn of the added/updated book.
   *
   *  This routine should set a `_lastModified` field in the book to
   *  the current Date timestamp.
   */
  async addBook(rawNameValues) {
    const nameValues = this._validate('addBook', rawNameValues);
    try {
      const _id = nameValues.isbn;
      const extras = { _id, _lastModified: new Date(), };
      const data = Object.assign({}, nameValues, extras);
      await this.books.updateOne({_id}, {$set: data}, { upsert: true });
      return _id;
    }
    catch (err) {
      throw [ new ModelError('DB', err.message || err.toString()) ];
    }
  }

  /** Given fields { isbn, authorsTitle, _count=COUNT, _index=0 } =
   *  nameValues, retrieve list of all books with specified isbn (if
   *  any) and the words specified in authorsTitle occurring in either
   *  the book's authors field or the title field.  The retrieved
   *  results are sorted in ascending order by title.  The returned
   *  results have up to _count books starting at index _index in the
   *  retrieved results.  The `_index` and `_count` fields allow
   *  paging through the search results.
   *
   *  Will return [] if no books match the search criteria.
   */
  async findBooks(rawNameValues) {
    const nameValues = this._validate('findBooks', rawNameValues);
    try {
      const query = {};
      const { authorsTitleSearch: $search, isbn: _id } = nameValues;
      if ($search !== undefined) query.$text = { $search, };
      if (_id !== undefined) query._id = _id;
      const index =
	nameValues._index !== undefined ? Number(nameValues._index) : 0;
      const count =
        nameValues._count !== undefined ? Number(nameValues._count) : COUNT;
      const cursor =
	await this.books.
	find(query).
	sort({title: 1 }).
        skip(index).
        limit(count);
      const results = await cursor.toArray();
      return results.map(obj => { const { _id, ...o } = obj; return o; });
    }
    catch (err) {
      throw [ new ModelError('DB', err.message || err.toString()) ];
    }
  }

  //wrapper around this.validator to verify that no external field
  //is _id which is used by mongo
  _validate(action, rawNameValues) {
    let errs = [];
    let nameValues;
    try {
      nameValues = this.validator.validate(action, rawNameValues);
    }
    catch (err) {
      if (err instanceof Array) { //something we understand
	errs = err;
      }
      else {
	throw err; //not expected, throw upstairs
      }
    }
    if (rawNameValues._id !== undefined) {
      errs.push(new ModelError('BAD_FIELD', '_id field not permitted', '_id'));
    }
    if (errs.length > 0) throw errs;
    return nameValues;
  }
  
};

//use as second argument to mongo.connect()
const MONGO_CONNECT_OPTIONS = { useUnifiedTopology: true };

//default value for _count in findBooks()
const COUNT = 5;

//define private constants and functions here.

const CARTS = 'carts';
const BOOKS = 'books';
